### ISSUE TITLE
Error 핸들링 (react-error-boundary) - 보류

### ISSUE THREAD

**Issue by LeeHanEum** [24-pre-capstone-design/Web#14]
### Error 핸들링
에러 발생시 RunTime Error 경고 페이지가 뜨며 컴포넌트가 깨지는 것을 방지해요.
react-error-boundary 라이브러리를 활용 대체 컴포넌트를 띄울 수 있게 합니다.
참고 공식 문서 : [https://ko.legacy.reactjs.org/docs/error-boundaries.html](url)

### task
- [x] 읽었으면 체크
- [ ] error 브랜치 생성
- [ ] react-error-bounday npm 설치
- [ ] 대체 컴포넌트 생성
- [ ] App.js에서 fallback -> 대체 컴포넌트 연동
- [ ] 테스트 후 pull request

4월 24일 23시 59분까지 pr 합니다.
