### ISSUE TITLE
대시보드 페이지

### ISSUE THREAD

**Issue by LeeHanEum** [24-pre-capstone-design/Web#4]
### 대시보드 페이지
주문, 매출액, 상품 목록 등을 한 눈에 확인할 수 있는 페이지 입니다.

### Tasks
- [x] 읽었으면 체크
- [x] dashboard 브랜치를 생성해주세요
- [x] 누적 주문량, 누적 매출액, 상품 목록, 최근 주문 등의 정보를 한 눈에 볼 수 있게 Grid 형식으로 구성하세요
- [x] 더미데이터를 만들고 화면에 보여지게 해주세요
- [x] 반응형으로 동작하도록 해주세요

### 유의사항
- 서버와 통신하지 않기 때문에 날짜 토클, 페이지네이션은 동작하지 않아도 됩니다.
- main 브랜치는 무중단 배포에 사용할 브랜치 이므로 꼭 develop 브랜치로 pr 해주세요.
- 기한 : 4월 9일 23시 59분

<img width="494" alt="Screenshot 2024-04-08 at 4 43 49 PM" src="https://github.com/24-pre-capstone-design/Web/assets/103233513/41d6cfc0-e01d-4f34-8247-e5c668ef9601">
